name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change if using a different default branch

permissions:
  contents: write  # Required for deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Use the Node.js version you prefer
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Next.js automatically exports to `out/`
          cname: alex-carlson.github.io  # Optional: Set a custom domain
